substitutions:
  _IMAGE_NAME: "image_name"
  _IMAGE_REGISTRY: "image_registery"
steps:
  # - id: 'Frontend tests'
  #   name: 'node:20.11.0-alpine'
  #   entrypoint: 'sh'
  #   args:
  #     - '-c'
  #     - |
  #       cd front
  #       echo 'Test frontend'
  - id: 'Docker build'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        docker build -t $_IMAGE_REGISTRY/$_IMAGE_NAME:$SHORT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
