steps:
  # Étape 1: Construire l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA']
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _SERVICE_NAME: run-tes
  _REGION: europe-west1
